### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by demure84** [shamatar/ElliKeyPublic#1]
So purchased this app and it's not even showing up when selected from the list of 3rd party keyboards? Please fix soon otherwise, this app isn't utterly useless if I can't even use it? 

Cheers. I well be asking for refund soon.

**Comment by shamatar** [comment]
Good evening, Demure84. 

Would you provide us with your iPhone model and iOS version?

**Comment by shamatar** [comment]
Also, what language do you use? 

Sincerely, development team

**Comment by demure84** [comment]
iPhone 6 Plus running 8.1.2 

English and Russian

**Comment by shamatar** [comment]
Good evening, demure84. 

We just tested the full process on iPhone 6, 8.1.3. 

Process was the following:
1) deactivate all keybords
2) remove the application
3) reinstall from the AppStore
4) launch the keyboard host application from main screen 
5) go to setting and activate necessary keyboards
6) go to main screen, pull down ( to activate search)
7) long press on "globe" button. Yes, there is a glitch here, not our keyboard related, but new keyboards do not appear in a list
8) pull up - close the search window 
9) pull down again
10) long press the globe button again, now keyboards should be in a list
11) to turn on autocorrects on "space" long press on "off" switch, it should switch to "on"

Sincerely, development team

**Comment by demure84** [comment]
Still not working, very disappointing when every other 3rd party keyboard lag showing up after being selected, this one just kicks into native iOS keyboard.

**Comment by demure84** [comment]
Please release an update.

**Comment by shamatar** [comment]
Good evening demure84. 

We will investigate this issue. There are iPhone6+ users with out application working for them. Would you provide us with your e-mail address, so we will include you in "TestFlight" program for the next release. 

Sincerely, development team
